sudo: required
dist: trusty

language: haxe

haxe:
 - "4.0.0-rc.4"

matrix:
 allow_failures:
   - haxe: "4.0.0-rc.4"

install:
 - haxelib install lime
 - haxelib install openfl
 - haxelib install flixel
 - haxelib install flixel-addons
 - haxelib install zerolib
 - haxelib dev zerolib-flixel .

script:
 - haxelib run lime build neko

deploy:
 - provider: script
   haxe: development
   script: bash ./release_haxelib.sh $HAXELIB_PWD
   on:
     tags: true